#rails defualt styling
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

#house style overrides
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
